apiVersion: v1
kind: PersistentVolume
metadata:
  name: hrsock-pv-gpuc-05
  labels:
    node: gpuc-05
    bind-to-pvc: hrsock-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/run/hrsock
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gpuc-05
