apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-gpuc-04
  labels:
    node: gpuc-04
    bind-to-pvc: redis-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/run/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gpuc-04
