apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      bind-to-pvc: redis-0